# Generated by Django 4.2.4 on 2023-09-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=60)),
            ],
        ),
    ]
