# Generated by Django 4.2.4 on 2023-09-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='Contact',
        ),
    ]
