# Generated by Django 3.0.5 on 2023-09-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_subcriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcriber',
            new_name='Subscriber',
        ),
    ]
