# Generated by Django 3.0.5 on 2023-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20230930_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Number', models.IntegerField()),
                ('form_email', models.EmailField(max_length=70, unique=True)),
                ('form_date', models.DateField()),
                ('choose_schedule', models.CharField(default='9 AM to 10 AM', max_length=20)),
            ],
        ),
    ]
