# Generated by Django 3.0.5 on 2023-10-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(max_length=13),
        ),
    ]
